### ISSUE TITLE
无法通过nuget添加TinyPinyin.Core

### ISSUE THREAD

**Issue by suihanhbr** [hstarorg/TinyPinyin.Net#1]
Attempting to gather dependency information for package 'TinyPinyin.Core.0.1.0' with respect to project 'SuiHanIME', targeting '.NETPortable,Version=v4.5,Profile=Profile7'
  GET https://www.nuget.org/api/v2/Packages(Id='TinyPinyin.Core',Version='0.1.0')
  OK https://www.nuget.org/api/v2/Packages(Id='TinyPinyin.Core',Version='0.1.0') 761ms
Total number of results gathered : 2
Gathering dependency information took 806.73 ms
Summary of time taken to gather dependencies per source :
https://www.nuget.org/api/v2/	-	776.36 ms
Attempting to resolve dependencies for package 'TinyPinyin.Core.0.1.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'TinyPinyin.Core.0.1.0'
Resolved actions to install package 'TinyPinyin.Core.0.1.0'
Retrieving package 'TinyPinyin.Core 0.1.0' from 'Official NuGet Gallery'.
  GET https://www.nuget.org/api/v2/package/TinyPinyin.Core/0.1.0
  OK https://www.nuget.org/api/v2/package/TinyPinyin.Core/0.1.0 3139ms
Acquiring lock for the installation of TinyPinyin.Core 0.1.0
Acquired lock for the installation of TinyPinyin.Core 0.1.0
Installing TinyPinyin.Core 0.1.0.
Completed installation of TinyPinyin.Core 0.1.0
For adding package 'TinyPinyin.Core.0.1.0' to project 'SuiHanIME' that targets 'portable45-net45+win8'.
Install failed. Rolling back...
Package 'TinyPinyin.Core.0.1.0' does not exist in project 'SuiHanIME'
Package 'TinyPinyin.Core.0.1.0' does not exist in folder '/Volumes/secondDisk/xamarin_workspace/SuiHanIME/packages'
Executing nuget actions took 3.91 sec
Could not install package 'TinyPinyin.Core 0.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by hstarorg** [comment]
请问你那边的Framework版本是多少呢？这边是用4.5进行发布的。

**Comment by suihanhbr** [comment]
我是尝试在xamarin工程中导入这个项目，是否不能用于xamarin？我这里是用的mono 5.0的样子。

**Comment by hstarorg** [comment]
没有使用过Xamarin。如果要在Xamarin中使用的话，我是建议直接将整个源代码引入。

**Comment by hstarorg** [comment]
暂无收到反馈。
