### ISSUE TITLE
Add support for .NET Standard

### ISSUE THREAD

**Issue by mzji** [hstarorg/TinyPinyin.Net#2]
考虑到这个库没有任何依赖项，是否可以考虑把Framework依赖版本改为.NET Standard 1.0？这样一来目前所有仍被微软支持的.NET平台都可以使用本库，而无需担心兼容性问题。
.NET Standard 1.0所支持的全部平台：根据[[1]](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.0.md)
- .NET Core 1.0
- .NET Framework 4.5
- Mono
- Xamarin.iOS
- Xamarin.Android
- Universal Windows Platform 10
- Windows 8.0
- Windows Phone 8.1
- Windows Phone Silverlight 8.0

具体修改流程请参考本文：[https://docs.microsoft.com/en-us/dotnet/core/packages](https://docs.microsoft.com/en-us/dotnet/core/packages)

**Comment by hstarorg** [comment]
好主意，打算加入到计划中，一个月之内搞定。也欢迎提PR。

**Comment by hstarorg** [comment]
https://www.nuget.org/packages/TinyPinyin.Core.Standard/

**Comment by mzji** [comment]
好顶赞！已更新依赖~

**Comment by hstarorg** [comment]
哈哈，其实一句代码没改。后面找时间，做成通用lib比较好，现在是独立发布的两个，不是很安逸。

**Comment by zhaobaolong** [comment]
我在.NET Framework 4.5 的mvc项目中通过Nuget安装TinyPinyin.Core.Standard 1.0.0 ，提示“无法安装程序包“TinyPinyin.Core.Standard 1.0.0”。你正在尝试将此程序包安装到目标为“.NETFramework,Version=v4.5”的项目中，但该程序包不包含任何与该框架兼容的程序集引用或内容文件。有关详细信息，请联系程序包作者。”
=========
 TinyPinyin.Core 也是同样的问题。

**Comment by mzji** [comment]
@zhaobaolong 目前TinyPinyin.Core.Standard的.Net目标是.Net Standard 1.6，兼容到.Net Framework 4.6.1
如果不够用的话，可以尝试下载源码手动降低.Net Standard版本看能否编译

**Comment by hstarorg** [comment]
@zhaobaolong 也可以直接安装 `TinyPinyin.Core`

**Comment by hstarorg** [comment]
问题已解决，关闭issue。

**Comment by sjtuross** [comment]
nuget上的库能否兼容 .netstandard 2.0，现在要求 .netstandard 2.1

**Comment by windy3417** [comment]
您好!您的邮件已收到,谢谢
