### ISSUE TITLE
 获取首字母时字符串中含有|字符会报超出索引范围

### ISSUE THREAD

**Issue by thePengLong** [hstarorg/TinyPinyin.Net#5]
获取首字母时这行代码会因为没有移除空白项导致超出索引范围会报错， `string.Join("", result.Split('|').Select(x => x.Substring(0, 1)).ToArray());  `

**Comment by simendancer** [comment]
> 

不用GetPinyinInitials，自己写一个方法就行了，或者自己改下源码
{
    string pinyin = GetPinyin(str,"|");
    return string.Join("",result.Split('|').Select(o => !string.IsNullOrWhiteSpace(o) && o.Length > 0 ? o.Substring(0,1) : o));
}

**Comment by hstarorg** [comment]
收到，感谢反馈，我这周 fix 一下~

**Comment by windy3417** [comment]
您好!您的邮件已收到,谢谢
